defaults:
  - _self_

model:
  name: "headway_stacked_gru"
  gru_units: [64, 32]
  dropout_rate: 0.0
  lookback_steps: 15
  forecast_steps: 1
  num_routes: 3
  route_ids: ["A", "C", "E"]

training:
  epochs: 50
  batch_size: 64
  learning_rate: 0.001
  optimizer: "adam"
  loss_function: "huber"

data:
  train_split: 0.6
  val_split: 0.20
  test_split: 0.20
  target_col: "headway_seconds"

experiment:
  project_id: "realtime-headway-prediction"
  location: "us-east1"
  name: "headway-prediction-experiments"
  run_name: "experiment-run-1"
  track_histograms: true
  histogram_freq: 1
  offline: false
  tensorboard_resource_name: "projects/realtime-headway-prediction/locations/us-east1/tensorboards/5815167465725886464"
  artifact_bucket: "ml-pipelines-headway-prediction"

pipeline:
  root: "gs://realtime-headway-prediction-pipelines/pipelines"
  bq_table_name: "headway_prediction.ml"
  data_lake_bucket: "headway-prediction-historic-data"

paths:
  input_path: null
  output_path: null
  model_output_path: null
  test_data_output_path: null
  model_path: null
  test_data_path: null
  output_metrics_path: null
  output_html_path: null
