# entrypoint for hydra defaults
defaults:
- _self_
- model: tft
- processing: default
- training: default
- infra: default

project_name: "realtime-headway-prediction"
experiment_name: "tft-model-retraining"
seed: 42